import { describe, expect, it } from "vitest";
import { demandFromCanonicalMetrics } from "@/server/lib/seo-intelligence/metric-demand";
import type { KeywordMetricObservation } from "@/server/lib/keyword-metrics/types";
const context = { normalizedQuery: "accounting software", language: "en", market: "US", searchObserved: true };
function metric(overrides: Partial<KeywordMetricObservation> & { searchVolume?: KeywordMetricObservation["searchVolume"]; evidence?: Partial<KeywordMetricObservation["evidence"]> } = {}): KeywordMetricObservation { return { id: "metric-1", queryId: "query-1", originalQuery: "accounting software", normalizedQuery: "accounting software", language: "en", market: "US", provider: "dataforseo", providerMetricType: "google_ads_search_volume", capturedAt: "2026-09-13T00:00:00.000Z", freshness: "KNOWN_CAPTURE_TIME", evidence: { family: "KEYWORD_METRIC", id: "raw", rawArtifactRef: "evidence/x", sha256: "a".repeat(64), captureId: "capture", ...overrides.evidence }, searchVolume: overrides.searchVolume ?? { status: "PRESENT", value: 10 }, cpc: { status: "MISSING", value: null }, paidAdvertiserCompetition: { status: "MISSING", value: null }, monthlySearches: [], providerMetadata: { locationCode: 2840, languageCode: "en", mappingVersion: "v1" }, ...overrides }; }
describe("canonical metric demand integration", () => {
  it("promotes only matching artifact-backed positive volume", () => { expect(demandFromCanonicalMetrics(context, [])).toBe("INDICATED"); expect(demandFromCanonicalMetrics(context, [metric()])).toBe("VALIDATED"); });
  it("keeps ZERO, NULL, MISSING, CPC, and competition non-validating", () => { for (const searchVolume of [{ status: "ZERO", value: 0 }, { status: "NULL", value: null }, { status: "MISSING", value: null }] as const) expect(demandFromCanonicalMetrics(context, [metric({ searchVolume })])).toBe("INDICATED"); expect(demandFromCanonicalMetrics(context, [metric({ searchVolume: { status: "MISSING", value: null }, cpc: { status: "PRESENT", value: 2.5 } })])).toBe("INDICATED"); });
  it("rejects wrong context and missing provenance", () => { expect(demandFromCanonicalMetrics(context, [metric({ market: "DE" })])).toBe("INDICATED"); expect(demandFromCanonicalMetrics(context, [metric({ language: "de" })])).toBe("INDICATED"); expect(demandFromCanonicalMetrics(context, [metric({ normalizedQuery: "other" })])).toBe("INDICATED"); expect(demandFromCanonicalMetrics(context, [metric({ evidence: { rawArtifactRef: "", sha256: "" } })])).toBe("INDICATED"); });
  it("is deterministic and does not acquire provider data during replay", () => { const observations = [metric(), metric({ id: "metric-2" })]; expect(demandFromCanonicalMetrics(context, observations)).toBe("VALIDATED"); expect(demandFromCanonicalMetrics(context, observations)).toBe("VALIDATED"); });
});
