import { describe, expect, it } from "vitest";
import { DataForSeoKeywordMetricAdapter } from "@/server/lib/keyword-metrics/dataforseo";
import { languageMappings, marketMappings, metricValue, qualifiesDemand } from "@/server/lib/keyword-metrics/types";
const evidence = { id: "raw-1", rawArtifactRef: "keyword-metrics/dataforseo/a.json", sha256: "a".repeat(64), captureId: "capture-1" };
const request = { queries: ["best accounting software for small business"], language: "en" as const, market: "US" as const };
function adapter(row: Record<string, unknown>) { return new DataForSeoKeywordMetricAdapter(async () => ({ rows: [row as { keyword: string }], capturedAt: "2026-09-13T00:00:00.000Z", evidence })); }
describe("canonical keyword metrics", () => {
  it("maps markets/languages and preserves populated paid-search metrics", async () => { const out = await adapter({ keyword: request.queries[0], search_volume: 120, cpc: 2.5, competition_index: 42, monthly_searches: [{ year: 2026, month: 2, search_volume: 100 }, { year: 2026, month: 1, search_volume: 90 }] }).fetchMetrics(request); expect(marketMappings.US.code).toBe(2840); expect(languageMappings.de).toBe("de"); expect(out.observations[0].paidAdvertiserCompetition.value).toBe(42); expect(out.observations[0]).not.toHaveProperty("organicSeoDifficulty"); expect(out.observations[0].monthlySearches.map(x => x.month)).toEqual([1, 2]); });
  it("distinguishes zero, missing, null, invalid, and qualifying context", async () => { expect(metricValue(0).status).toBe("ZERO"); expect(metricValue(undefined).status).toBe("MISSING"); expect(metricValue(null).status).toBe("NULL"); expect(metricValue(-1).status).toBe("INVALID"); const zero = (await adapter({ keyword: request.queries[0], search_volume: 0 }).fetchMetrics(request)).observations[0]; expect(qualifiesDemand(zero, { normalizedQuery: zero.normalizedQuery, language: "en", market: "US" })).toBe(false); const good = (await adapter({ keyword: request.queries[0], search_volume: 10 }).fetchMetrics(request)).observations[0]; expect(qualifiesDemand(good, { normalizedQuery: good.normalizedQuery, language: "en", market: "US" })).toBe(true); expect(qualifiesDemand(good, { normalizedQuery: good.normalizedQuery, language: "de", market: "DE" })).toBe(false); });
  it("does not refetch during canonical observation replay", async () => { let calls = 0; const provider = new DataForSeoKeywordMetricAdapter(async () => { calls++; return { rows: [{ keyword: request.queries[0], search_volume: 10 }], capturedAt: "2026-09-13T00:00:00.000Z", evidence }; }); const stored = await provider.fetchMetrics(request); const replay = () => qualifiesDemand(stored.observations[0], { normalizedQuery: stored.observations[0].normalizedQuery, language: "en", market: "US" }); expect(replay()).toBe(true); expect(replay()).toBe(true); expect(calls).toBe(1); });
});
