import { describe, expect, it } from "vitest";
import { acquireRawKeywordMetrics } from "@/server/lib/keyword-metrics/raw-acquisition";
const request = { queries: ["x"], language: "en" as const, market: "US" as const };
describe("raw metric acquisition", () => {
  const artifact = { ref: "evidence/keyword_metric/dataforseo/x.json", sha256: "a".repeat(64), capturedAt: "x", provider: "dataforseo", adapterVersion: "x", family: "KEYWORD_METRIC" as const, contentType: "application/json" };
  it("captures exact bytes before parse", async () => { const bytes = new TextEncoder().encode('{"ok":true}'); const seen: Uint8Array[] = []; const result = await acquireRawKeywordMetrics(new Response(bytes), request, { captureArtifact: async (x) => { seen.push(x.bytes); return artifact; } }); expect(result.kind).toBe("SUCCESS"); expect(seen[0]).toEqual(bytes); });
  it.each([[401, '{"error":"unauthorized"}'], [429, '{"error":"rate_limited"}'], [500, '{"error":"upstream_failure"}']])( "captures HTTP %i error bytes before returning failure", async (status, body) => { const bytes = new TextEncoder().encode(body); const seen: Uint8Array[] = []; const result = await acquireRawKeywordMetrics(new Response(bytes, { status }), request, { captureArtifact: async (x) => { seen.push(x.bytes); return artifact; } }); expect(result).toMatchObject({ kind: "HTTP_PROVIDER_FAILURE", status, artifact: { ref: artifact.ref, sha256: artifact.sha256 } }); expect(seen).toEqual([bytes]); });
  it("gives persistence failure precedence and retains parse artifacts", async () => { const fail = await acquireRawKeywordMetrics(new Response("{}", { status: 401 }), request, { captureArtifact: async () => { throw new Error("r2 down"); } }); expect(fail.kind).toBe("EVIDENCE_PERSISTENCE_FAILURE"); const parse = await acquireRawKeywordMetrics(new Response("no"), request, { captureArtifact: async () => artifact }); expect(parse).toMatchObject({ kind: "PARSE_FAILURE", artifact: { ref: artifact.ref } }); });
});
