import { describe, expect, it } from "vitest";
import { acquireDataForSeoKeywordMetrics } from "@/server/lib/keyword-metrics/dataforseo";
import type { ImmutableEvidenceStore } from "@/server/lib/serp-providers/evidence";
const request = { queries: ["accounting software", "small business accounting software"], language: "en" as const, market: "US" as const };
const artifact = { ref: "evidence/keyword_metric/dataforseo/rows.json", sha256: "c".repeat(64), capturedAt: "2026-09-13T00:00:00.000Z", provider: "dataforseo", adapterVersion: "phase-3a", family: "KEYWORD_METRIC" as const, contentType: "application/json" };
function run(result: unknown, queries = request.queries) { let calls = 0; const evidence: ImmutableEvidenceStore = { captureArtifact: async () => { calls++; return artifact; } }; return { calls: () => calls, promise: acquireDataForSeoKeywordMetrics({ ...request, queries }, { execute: async () => new Response(JSON.stringify({ tasks: [{ status_code: 20000, result }] })) }, evidence) }; }
describe("keyword metric row semantics", () => {
  it("maps reverse-order rows to distinct observations sharing one artifact", async () => { const f = run([{ keyword: request.queries[1], search_volume: 20 }, { keyword: request.queries[0], search_volume: 10 }]); const result = await f.promise; expect(result).toMatchObject({ kind: "SUCCESS" }); expect(result.observations).toHaveLength(2); expect(f.calls()).toBe(1); expect(new Set(result.observations.map(x => x.evidence.rawArtifactRef))).toEqual(new Set([artifact.ref])); expect(new Set(result.observations.map(x => x.queryId)).size).toBe(2); });
  it("records missing rows with artifact lineage without fabricating zero", async () => { const result = await run([{ keyword: request.queries[0], search_volume: 10 }]).promise; expect(result.observations).toHaveLength(1); expect(result.missingRows).toEqual([{ query: request.queries[1], reason: "MISSING_PROVIDER_ROW", artifactRef: artifact.ref, sha256: artifact.sha256 }]); });
  it("rejects duplicate provider rows", async () => { const result = await run([{ keyword: request.queries[0], search_volume: 10 }, { keyword: request.queries[0], search_volume: 10 }], [request.queries[0]]).promise; expect(result).toMatchObject({ kind: "DUPLICATE_PROVIDER_ROW", observations: [], artifact: { ref: artifact.ref } }); });
  it("preserves explicit zero and missing volume as distinct field states", async () => { const zero = await run([{ keyword: request.queries[0], search_volume: 0 }], [request.queries[0]]).promise; expect(zero.observations[0].searchVolume).toEqual({ status: "ZERO", value: 0 }); const missing = await run([{ keyword: request.queries[0], cpc: 2.5, competition_index: 42 }], [request.queries[0]]).promise; expect(missing.observations[0]).toMatchObject({ searchVolume: { status: "MISSING", value: null }, cpc: { status: "PRESENT", value: 2.5 }, paidAdvertiserCompetition: { status: "PRESENT", value: 42 } }); });
});
