import { createHash } from "node:crypto";
export type MetricStatus = "PRESENT" | "ZERO" | "MISSING" | "NULL" | "UNSUPPORTED" | "INVALID" | "STALE";
export type CanonicalKeywordMetricRequest = { queries: string[]; language: "en" | "de" | "fr" | "es" | "it" | "nl"; market: "US" | "UK" | "DE" | "NL" | "CH" | "IN" };
export type MetricValue<T> = { status: MetricStatus; value: T | null };
export type KeywordMetricObservation = { id: string; queryId: string; originalQuery: string; normalizedQuery: string; language: string; market: string; provider: "dataforseo"; providerMetricType: "google_ads_search_volume" | "labs_keyword_overview"; capturedAt: string; freshness: "KNOWN_CAPTURE_TIME"; evidence: { family: "KEYWORD_METRIC"; id: string; rawArtifactRef: string; sha256: string; captureId: string }; searchVolume: MetricValue<number>; cpc: MetricValue<number>; paidAdvertiserCompetition: MetricValue<number>; monthlySearches: { year: number; month: number; searchVolume: MetricValue<number> }[]; providerMetadata: { locationCode: number; languageCode: string; mappingVersion: string } };
export type MetricFailure = { code: "CREDENTIALS_MISSING" | "AUTHENTICATION" | "RATE_LIMIT" | "TIMEOUT" | "NETWORK" | "MALFORMED_RESPONSE" | "TASK_FAILURE" | "MISSING_QUERY_ROW" | "UNKNOWN_LOCATION" | "UNKNOWN_LANGUAGE"; message: string };
export interface KeywordMetricProvider { fetchMetrics(request: CanonicalKeywordMetricRequest): Promise<{ observations: KeywordMetricObservation[]; failures: MetricFailure[] }> }
export const marketMappings = { US: { code: 2840, name: "United States" }, UK: { code: 2826, name: "United Kingdom" }, DE: { code: 2276, name: "Germany" }, NL: { code: 2528, name: "Netherlands" }, CH: { code: 2756, name: "Switzerland" }, IN: { code: 2356, name: "India" } } as const;
export const languageMappings = { en: "en", de: "de", fr: "fr", es: "es", it: "it", nl: "nl" } as const;
export function metricValue(value: unknown): MetricValue<number> { if (value === undefined) return { status: "MISSING", value: null }; if (value === null) return { status: "NULL", value: null }; if (typeof value !== "number" || !Number.isFinite(value) || value < 0) return { status: "INVALID", value: null }; return { status: value === 0 ? "ZERO" : "PRESENT", value }; }
export function metricObservationId(query: string, language: string, market: string, sha256: string): string { return `metric_${createHash("sha256").update(`${query.normalize("NFKC").trim().toLowerCase()}|${language}|${market}|${sha256}`).digest("hex").slice(0, 24)}`; }
export function qualifiesDemand(observation: KeywordMetricObservation, context: { normalizedQuery: string; language: string; market: string }): boolean { return observation.searchVolume.status === "PRESENT" && observation.normalizedQuery === context.normalizedQuery && observation.language === context.language && observation.market === context.market && Boolean(observation.evidence.rawArtifactRef) && /^[a-f0-9]{64}$/.test(observation.evidence.sha256); }
