import { createHash } from "node:crypto";
import type { CanonicalCompetitorInput, CommercialSignal, CompetitorObservation, DemandState, EvidenceRef, IntelligenceInput, IntelligenceReport, IntentAssessment, IntentClass, JTBD, NextValidationAction, ProblemSignal, QueryObservation, UnknownRecord } from "@/server/lib/seo-intelligence/types";
import { SEO_INTELLIGENCE_SCHEMA_VERSION, SEO_INTELLIGENCE_VERSION } from "@/server/lib/seo-intelligence/types";

export function normalizeQuery(query: string): string { return query.normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleLowerCase("und"); }
export function queryIdentity(query: Pick<QueryObservation, "normalizedQuery" | "engine" | "language" | "region">): string { return `query_${createHash("sha256").update(JSON.stringify([query.normalizedQuery, query.engine, query.language, query.region])).digest("hex").slice(0, 24)}`; }
const has = (query: string, phrase: string) => new RegExp(`(^|\\s)${phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(?=\\s|$)`, "i").test(query);

export function assessIntent(query: string, evidence: EvidenceRef): IntentAssessment {
  const q = normalizeQuery(query); const basis: string[] = []; let intent: IntentClass = "unknown";
  if (/\bnear me\b/.test(q)) { intent = "local"; basis.push("near me"); }
  else if (/\b(pricing|price|buy|purchase)\b/.test(q)) { intent = "transactional"; basis.push("purchase/pricing term"); }
  else if (/\b(vs|versus|alternative|best)\b/.test(q)) { intent = "commercial_investigation"; basis.push("comparison term"); }
  else if (/^(what is|how to|why )/.test(q)) { intent = "informational"; basis.push("question wording"); }
  return { intent, confidence: basis.length ? 0.7 : 0.2, basis, evidenceRefs: [evidence.id], category: "DERIVED" };
}
export function commercialSignals(query: string, evidence: EvidenceRef): CommercialSignal[] {
  const rules: Array<[CommercialSignal["type"], RegExp, string]> = [["pricing", /\b(pricing|price)\b/i, "pricing term"], ["comparison", /\b(vs|versus|best)\b/i, "comparison term"], ["alternative", /\balternative(s)?\b/i, "alternative term"], ["purchase", /\b(buy|purchase)\b/i, "purchase term"], ["software_tool", /\b(software|tool|app)\b/i, "tool term"], ["service_provider", /\bagency\b/i, "agency term"], ["local_service", /\bnear me\b/i, "local term"]];
  return rules.filter(([, re]) => re.test(query)).map(([type,, matchedBasis]) => ({ type, matchedBasis, confidence: 0.65, source: "DETERMINISTIC", evidence }));
}
export function problemSignals(query: string, evidence: EvidenceRef): ProblemSignal[] {
  const rules: Array<[ProblemSignal["category"], RegExp]> = [["how_to", /^how to\b/i], ["why", /^why\b/i], ["fix", /^fix\b/i], ["remove", /^remove\b/i], ["convert", /^convert\b/i], ["download", /^download\b/i], ["constraint", /\bwithout\b/i], ["automation", /\bautomatically\b/i], ["best_way", /^best way to\b/i], ["tool_app", /\b(tool|app) for\b/i], ["alternative", /\balternative to\b/i], ["value", /\b(cheaper|faster) than\b/i]];
  return rules.filter(([, re]) => re.test(query)).map(([category]) => ({ category, query, confidence: 0.7, directlyObserved: true, evidence }));
}
export function competitorsFromCanonical(queryId: string, rows: CanonicalCompetitorInput[]): CompetitorObservation[] { return rows.filter((row) => row.destinationIdentity === "VERIFIED_DESTINATION" && row.destinationUrlUsable && row.destinationDomainUsable && row.domain && row.url).map((row): CompetitorObservation => ({ type: "SERP_COMPETITOR", domain: row.domain!, url: row.url!, queryId, organicPosition: row.organicPosition, title: row.title, snippet: row.snippet, evidence: row.evidence })).sort((a, b) => a.organicPosition - b.organicPosition || a.domain.localeCompare(b.domain)); }
export function classifyDemand(signals: IntelligenceInput["signals"], inspection?: "NOT_VALIDATED"): DemandState { return signals.some((signal) => signal.type === "KEYWORD_METRIC" && signal.evidence.category === "PROVIDER_METRIC") ? "VALIDATED" : inspection === "NOT_VALIDATED" ? "NOT_VALIDATED" : signals.some((signal) => signal.evidence.category === "SEARCH_OBSERVED") ? "INDICATED" : "UNKNOWN"; }
function jtbd(query: string, evidence: EvidenceRef): JTBD { const task = /^(how to|remove|download|fix|convert)\s+(.+)/i.exec(query); return task ? { actor: null, task: task[2], desiredOutcome: null, constraint: /\bwithout\b/i.test(query) ? "without constraint observed" : null, basis: "OBSERVED", evidenceRefs: [evidence.id] } : { actor: null, task: null, desiredOutcome: null, constraint: null, basis: "INFERRED", evidenceRefs: [evidence.id] }; }
function nextAction(demandState: DemandState, competitors: CompetitorObservation[], evidence: EvidenceRef): NextValidationAction { return demandState !== "VALIDATED" ? { type: "OBTAIN_KEYWORD_METRIC", reason: "Demand is not supported by a verified provider metric.", evidenceRefs: [evidence.id] } : competitors.length ? { type: "INSPECT_TOP_COMPETITORS", reason: "Verified SERP competitors require product/content inspection.", evidenceRefs: competitors.map((c) => c.evidence.id) } : { type: "VALIDATE_MARKET_LOCALIZATION", reason: "No verified destination competitors were available.", evidenceRefs: [evidence.id] }; }
export function deriveIntelligence(input: IntelligenceInput): IntelligenceReport {
  const query = { ...input.observation, normalizedQuery: normalizeQuery(input.observation.originalQuery) }; const queryId = queryIdentity(query); const intent = assessIntent(query.originalQuery, query.evidence); const commercial = commercialSignals(query.originalQuery, query.evidence); const problems = problemSignals(query.originalQuery, query.evidence); const competitors = competitorsFromCanonical(queryId, input.competitors); const demandState = classifyDemand(input.signals, input.demandInspection); const unknowns: UnknownRecord[] = demandState === "VALIDATED" ? [] : [{ topic: "search_demand", reason: "No verified provider metric supports demand.", evidenceRefs: [query.evidence.id] }]; if (!competitors.length) unknowns.push({ topic: "competitor_destination", reason: "No verified destination identity was available.", evidenceRefs: [query.evidence.id] }); const action = nextAction(demandState, competitors, query.evidence); const opportunity = { id: `opportunity_${queryId}`, queryId, demandState, intent, problemSignals: problems, commercialSignals: commercial, competitors, evidenceRefs: Array.of(query.evidence.id), unknowns, confidence: demandState === "VALIDATED" && commercial.length ? "PROMISING" : commercial.length || problems.length ? "EMERGING" : "WEAK", nextAction: action } as const;
  return { schema_version: SEO_INTELLIGENCE_SCHEMA_VERSION, intelligence_version: SEO_INTELLIGENCE_VERSION, generated_at: query.capturedAt, source_observation_ids: [query.id], configuration_version: input.configurationVersion, observed: { query, signals: [...input.signals].sort((a, b) => a.type.localeCompare(b.type)), competitors }, derived: { demand: demandState, intent, commercialSignals: commercial, problemSignals: problems, jtbd: jtbd(query.originalQuery, query.evidence), opportunity }, model_inferred: [], unknowns, contradictions: [], next_validation_actions: [action] };
}
