import { normalizeQuery } from "@/server/lib/seo-intelligence/deterministic";
import type { IntelligenceInput, QueryObservation } from "@/server/lib/seo-intelligence/types";

function observation(query: string, id: string): QueryObservation {
  const evidence = { id: `evidence-${id}`, category: "SEARCH_OBSERVED" as const, sourceObservationId: id, captureId: `capture-${id}` };
  return { id, originalQuery: query, normalizedQuery: normalizeQuery(query), sourceType: "organic_serp", sourceProvider: "fixture", engine: "google", language: "en", region: "US", capturedAt: "2026-09-13T00:00:00.000Z", evidence };
}
export const controlledFixtures: Record<string, IntelligenceInput> = {
  commercialComparison: { observation: observation("best accounting software for small business", "case-a"), signals: [{ type: "OBSERVED_ORGANIC_SERP_QUERY", evidence: { id: "evidence-case-a", category: "SEARCH_OBSERVED", sourceObservationId: "case-a", captureId: "capture-case-a" } }], competitors: [{ destinationIdentity: "VERIFIED_DESTINATION", destinationUrlUsable: true, destinationDomainUsable: true, domain: "example.com", url: "https://example.com/pricing", organicPosition: 1, title: "Example", snippet: null, evidence: { id: "evidence-case-a", category: "SEARCH_OBSERVED", sourceObservationId: "case-a", captureId: "capture-case-a" } }], configurationVersion: "phase-2-fixtures-v1" },
  directProblem: { observation: observation("remove background from image", "case-b"), signals: [{ type: "OBSERVED_ORGANIC_SERP_QUERY", evidence: { id: "evidence-case-b", category: "SEARCH_OBSERVED", sourceObservationId: "case-b", captureId: "capture-case-b" } }], competitors: [], configurationVersion: "phase-2-fixtures-v1" },
  utilityTask: { observation: observation("download youtube comments", "case-c"), signals: [{ type: "USER_PROVIDED_QUERY", evidence: { id: "evidence-case-c", category: "USER_PROVIDED", sourceObservationId: "case-c", captureId: "capture-case-c" } }], competitors: [], configurationVersion: "phase-2-fixtures-v1" },
  localService: { observation: observation("seo agency near me", "case-d"), signals: [{ type: "OBSERVED_ORGANIC_SERP_QUERY", evidence: { id: "evidence-case-d", category: "SEARCH_OBSERVED", sourceObservationId: "case-d", captureId: "capture-case-d" } }], competitors: [], configurationVersion: "phase-2-fixtures-v1" },
  informational: { observation: observation("what is schema markup", "case-e"), signals: [{ type: "OBSERVED_ORGANIC_SERP_QUERY", evidence: { id: "evidence-case-e", category: "SEARCH_OBSERVED", sourceObservationId: "case-e", captureId: "capture-case-e" } }], competitors: [], configurationVersion: "phase-2-fixtures-v1" },
  ambiguous: { observation: observation("atlas", "case-f"), signals: [{ type: "USER_PROVIDED_QUERY", evidence: { id: "evidence-case-f", category: "USER_PROVIDED", sourceObservationId: "case-f", captureId: "capture-case-f" } }], competitors: [{ destinationIdentity: "WRAPPER_ONLY", destinationUrlUsable: false, destinationDomainUsable: false, domain: null, url: null, organicPosition: 1, title: "Wrapped", snippet: null, evidence: { id: "evidence-case-f", category: "SEARCH_OBSERVED", sourceObservationId: "case-f", captureId: "capture-case-f" } }], configurationVersion: "phase-2-fixtures-v1" },
};
