import { describe, expect, it } from "vitest";
import { createR2RawEvidenceStore } from "@/server/lib/serp-providers/evidence";
import { demandFromCanonicalMetrics } from "@/server/lib/seo-intelligence/metric-demand";
import { corroborateEvidence, type CorroborationEvidence } from "@/server/lib/seo-intelligence/corroboration";
import { processMarketSources, replayMarketEvidence, type MarketRawSource } from "@/server/lib/seo-intelligence/market-evidence";

function memoryStore() { const values = new Map<string, { bytes: Uint8Array; contentType: string }>(); const bucket = { head: async (key: string) => values.has(key) ? {} : null, put: async (key: string, value: Uint8Array, options: { httpMetadata: { contentType: string } }) => { values.set(key, { bytes: value, contentType: options.httpMetadata.contentType }); } } as unknown as R2Bucket; return { store: createR2RawEvidenceStore(bucket), values }; }
const source = (claimKind: MarketRawSource["claimKind"], text: string, sourceId: string): MarketRawSource => ({ sourceClass: "PUBLIC_REGISTRY", sourceId, sourceUrl: "https://registry.test/us/software", sourceDomain: "registry.test", capturedAt: "2026-09-13T00:00:00.000Z", provider: "market-fixture", targetGeography: "US", observedGeography: "US", claimKind, claimKey: `${claimKind}:invoice-software:US`, text, normalizedValue: "invoice software", stance: "SUPPORTS" });

describe("market evidence vertical slice", () => {
  it("captures traceable market claims with exact bytes, lineage, geography, and all bounded types", async () => {
    const { store, values } = memoryStore(); const inputs = [source("MARKET_PRESENCE", "Invoice software suppliers are listed in the US registry.", "presence"), source("CATEGORY_ACTIVITY", "The invoice software category is active in the US.", "activity"), source("COMMERCIAL_AVAILABILITY", "Invoice software is commercially available in the US.", "availability"), source("GEOGRAPHIC_PRESENCE", "Invoice software providers operate in the US.", "geography"), source("MARKET_CONSTRAINT", "US registry access requires a business registration.", "constraint")]; const result = await processMarketSources(inputs, store);
    expect(result.observations).toHaveLength(5); expect(result.unknowns).toEqual([]); for (const observation of result.observations) { expect(observation).toMatchObject({ family: "MARKET", targetGeography: "US", sourceDomain: "registry.test", category: "SITE_OBSERVED", evidenceFunction: "MARKET_CONTEXT", limits: "OBSERVED_MARKET_CLAIM_ONLY", evidence: { family: "MARKET" } }); expect(observation.evidence.sha256).toHaveLength(64); expect(values.get(observation.evidence.rawArtifactRef)).toMatchObject({ bytes: new TextEncoder().encode(observation.observedText), contentType: "text/plain" }); }
  });
  it("rejects untraceable and model-inferred sources, missing provenance, and wrong geography without observations", async () => {
    const { store } = memoryStore(); const result = await processMarketSources([{ ...source("MARKET_PRESENCE", "Anonymous summary.", "untraceable"), sourceClass: "UNTRACEABLE" }, { ...source("MARKET_PRESENCE", "Model summary.", "model-inferred"), sourceClass: "MODEL_INFERRED" }, { ...source("MARKET_PRESENCE", "Missing source ID.", "missing"), sourceId: null }, { ...source("MARKET_PRESENCE", "US observation.", "wrong-geo"), targetGeography: "DE" }], store);
    expect(result).toMatchObject({ observations: [], unknowns: [{ reason: "SOURCE_REJECTED" }, { reason: "SOURCE_REJECTED" }, { reason: "INSUFFICIENT_PROVENANCE" }, { reason: "GEOGRAPHY_MISMATCH" }], admissions: [{ outcome: "REJECTED" }, { outcome: "REJECTED" }, { outcome: "UNKNOWN_INSUFFICIENT_PROVENANCE" }, { outcome: "UNKNOWN_GEOGRAPHY_MISMATCH" }] });
  });
  it("preserves contradictory market observations as open without merging values", async () => {
    const { store } = memoryStore(); const result = await processMarketSources([source("COMMERCIAL_AVAILABILITY", "Invoice software is commercially available in the US.", "available"), { ...source("COMMERCIAL_AVAILABILITY", "Invoice software is not commercially available in the US.", "unavailable"), stance: "CONTRADICTS" }], store);
    expect(result.observations).toHaveLength(2); expect(result.contradictions).toMatchObject([{ status: "OPEN", nextAction: "COLLECT_MARKET_EVIDENCE" }]); expect(result.contradictions[0].supportingObservationIds).toHaveLength(1); expect(result.contradictions[0].conflictingObservationIds).toHaveLength(1);
  });
  it("keeps other evidence families from manufacturing market evidence and market from entering them", async () => {
    const { store } = memoryStore(); const metricShaped = { searchVolume: { status: "PRESENT", value: 120 }, evidence: { family: "KEYWORD_METRIC" } } as unknown as MarketRawSource; const buyerShaped = { sourceClass: "SITE_CAPTURED", evidence: { family: "BUYER_LANGUAGE" } } as unknown as MarketRawSource; const competitorShaped = { sourceClass: "COMPETITOR_PAGE", evidence: { family: "COMPETITOR" } } as unknown as MarketRawSource;
    expect(await processMarketSources([metricShaped, buyerShaped, competitorShaped], store)).toMatchObject({ observations: [], admissions: [{ outcome: "REJECTED" }, { outcome: "REJECTED" }, { outcome: "REJECTED" }] }); const marketResult = await processMarketSources([source("MARKET_PRESENCE", "Invoice software suppliers are listed in the US registry.", "market")], store); expect(demandFromCanonicalMetrics({ normalizedQuery: "invoice software", language: "en", market: "US", searchObserved: true }, [])).toBe("INDICATED"); const marketShaped = { id: marketResult.observations[0].id, family: "MARKET", propositionId: marketResult.observations[0].normalizedPropositionId, propositionType: "PROBLEM_EXISTS", stance: "SUPPORTS", rawArtifactRef: marketResult.observations[0].evidence.rawArtifactRef, sha256: marketResult.observations[0].evidence.sha256 } as unknown as CorroborationEvidence; expect(corroborateEvidence([marketShaped])[0].status).toBe("UNKNOWN");
  });
  it("replays stored canonical market evidence without refetching", async () => { const { store } = memoryStore(); let fetches = 0; const first = await processMarketSources([source("MARKET_PRESENCE", "Invoice software suppliers are listed in the US registry.", "replay")], store); expect(replayMarketEvidence(first)).toEqual(first); expect(fetches).toBe(0); expect(first).not.toHaveProperty("opportunityScore"); expect(first).not.toHaveProperty("decision"); });
});
