import { describe, expect, it } from "vitest";
import { assembleEvidenceSynthesis, replayEvidenceSynthesis, type SynthesisInput, type StoredSynthesisEvidence } from "@/server/lib/seo-intelligence/synthesis";

const context = { targetQuery: "invoice automation", targetLanguage: "en", targetMarket: "US", targetTopicId: "invoice-automation" };
const propositionId = "invoice-automation";
const evidence = (family: StoredSynthesisEvidence["family"], id: string, artifact = `evidence/${id}`, sha = id.padEnd(64, "a")): StoredSynthesisEvidence => ({ id, family, propositionId, propositionType: "FEATURE_MATCH", artifactRef: artifact, sha256: sha, context: family === "MARKET" || family === "SEARCH_DEMAND" ? context : { targetQuery: null, targetLanguage: null, targetMarket: null, targetTopicId: null } });
function input(items: StoredSynthesisEvidence[], overrides: Partial<SynthesisInput> = {}): SynthesisInput { return { target: { propositionId, propositionType: "FEATURE_MATCH", ...context }, evidence: items, corroboration: [], contradictions: [], unknowns: [], generatedAt: null, ...overrides }; }

describe("canonical evidence synthesis", () => {
  it("assembles all frozen families with complete lineage and immutable inputs", () => { const values = [evidence("SEARCH_DEMAND", "demand"), evidence("BUYER_LANGUAGE", "buyer"), evidence("COMPETITOR", "competitor"), evidence("MARKET", "market")]; const before = structuredClone(values); const result = assembleEvidenceSynthesis(input(values)); expect(result).toMatchObject({ kind: "SUCCESS", record: { synthesisStatus: "ASSEMBLED", familyPresence: { SEARCH_DEMAND: "PRESENT", BUYER_LANGUAGE: "PRESENT", COMPETITOR: "PRESENT", MARKET: "PRESENT" } } }); if (result.kind === "SUCCESS") { expect(result.record.supportingArtifactRefs).toHaveLength(4); expect(result.record.supportingShas).toHaveLength(4); } expect(values).toEqual(before); });
  it("keeps partial coverage, mismatches, wrong context, and unknowns explicit", () => { const partial = assembleEvidenceSynthesis(input([evidence("BUYER_LANGUAGE", "buyer"), evidence("COMPETITOR", "competitor")])); expect(partial).toMatchObject({ kind: "SUCCESS", record: { synthesisStatus: "PARTIAL" } }); const mismatch = assembleEvidenceSynthesis(input([{ ...evidence("MARKET", "de-market"), context: { ...context, targetMarket: "DE" } }], { unknowns: [{ id: "unknown-provenance", propositionId, context }] })); expect(mismatch).toMatchObject({ kind: "SUCCESS", record: { synthesisStatus: "UNKNOWN", unknownRefs: ["unknown-provenance"] } }); });
  it("propagates unresolved contradictions and rejects shared lineage as independent", () => { const contradicted = assembleEvidenceSynthesis(input([evidence("BUYER_LANGUAGE", "buyer"), evidence("COMPETITOR", "competitor")], { contradictions: [{ id: "open-conflict", propositionId, context } ] })); expect(contradicted).toMatchObject({ kind: "SUCCESS", record: { synthesisStatus: "CONTRADICTED", contradictionRefs: ["open-conflict"] } }); const shared = assembleEvidenceSynthesis(input([evidence("BUYER_LANGUAGE", "buyer", "evidence/shared", "s".repeat(64)), evidence("COMPETITOR", "competitor", "evidence/shared", "s".repeat(64)), evidence("MARKET", "market"), evidence("SEARCH_DEMAND", "demand")])); expect(shared).toMatchObject({ kind: "SUCCESS", record: { synthesisStatus: "PARTIAL", evidenceGaps: expect.arrayContaining(["independence:shared-lineage"]) } }); });
  it("requires B9 underlying buyer and competitor refs and replays without refetching", () => { const values = [evidence("BUYER_LANGUAGE", "buyer"), evidence("COMPETITOR", "competitor")]; const valid = assembleEvidenceSynthesis(input(values, { corroboration: [{ id: "b9", normalizedPropositionId: propositionId, supportingEvidenceRefs: ["buyer", "competitor"], artifactRefs: [], shas: [], status: "CORROBORATED" } as never] })); expect(valid).toMatchObject({ kind: "SUCCESS", record: { corroborationRefs: ["b9"] } }); const invalid = assembleEvidenceSynthesis(input(values, { corroboration: [{ id: "bad-b9", normalizedPropositionId: propositionId, supportingEvidenceRefs: [], artifactRefs: [], shas: [], status: "CORROBORATED" } as never] })); expect(invalid).toMatchObject({ kind: "SUCCESS", record: { unknownRefs: ["bad-b9"] } }); let fetches = 0; if (valid.kind === "SUCCESS") expect(replayEvidenceSynthesis(valid.record)).toEqual(valid.record); expect(fetches).toBe(0); });
  it("rejects score or verdict fields by contract", () => { expect(assembleEvidenceSynthesis({ ...input([evidence("BUYER_LANGUAGE", "buyer")]), opportunityScore: 99 } as unknown as SynthesisInput)).toEqual({ kind: "CONTRACT_VIOLATION", reason: "FORBIDDEN_SCORE_OR_DECISION_FIELD" }); expect(assembleEvidenceSynthesis({ ...input([evidence("BUYER_LANGUAGE", "buyer")]), decision: "BUILD" } as unknown as SynthesisInput)).toEqual({ kind: "CONTRACT_VIOLATION", reason: "FORBIDDEN_SCORE_OR_DECISION_FIELD" }); });
});
